language: c
sudo: required
before_install:
- sudo apt-get update
script:
- python3 --version
- python3 .travis/slack_notification.py
after_script:
- echo 'running after_script'
notifications:
  slack:
    rooms:
     - secure: bJXAZ2TpgDjPuMu7MvHocI64I6ta3zI/2zEifNvOdKr+rHlydessjuvoxqQWz+aCOZeuAALK47xukoHIfJVfs445xlp1MxoZICzjJjubsd6jHioSwJlExPJMsieBoZEBZtBnARApd1NNCiYrgHYCu+klKFCp9KuGMDTxNssePrSggNcQJLXbt2amgHoyzpKhbXZqgXex5BZdBCw4N8xE79Q8mU5YcuP4JYFA/vydz5J+CLNL0h3DooTrNy3HYL+3a37CFe/B2l0rSbGMsFmQpsdOMF9f5Pf6qrg+245LDoVbZ8Y9/zlFaISGM6y+g6XMP+Q1hEdVCjDclkx3/sCVX+vn2DIO7qR6KSLg3vH43dGtE0ckrO9O8+A0l4iCKvl1VAd9PYHBgwOaqgHn9/13KO1sCzGXHJ51RGxs5bjsTvd1rqn9oaJNy+HKU8NpX/X7rEN6Nf4ivqyryfgftTzxUYL1/tZ8+jHQJ+XFlpZc2+8dX/gkQGdoHUobHD39mjRAo17qcupbFOXt6fGnXn9FL6IfIi9X2s6GJJRqGtrPdPpqeSSWs2PnNQqQHZeYvoUxMaeuGEPdewmxY7/5fPVwTcKYWQ81eqTOo0vEN2jZ+y6BiEqjh9RvwoJSTChBCi3wcTowxbyq2ClbzCrRSgnhaleMGl2XDgjpr/TzJyurzmw=
    on_success: always
    on_failure: always
