language: c
sudo: required
before_install:
- sudo apt-get update
- sudo apt install -y software-properties-common
- sudo add-apt-repository -y ppa:deadsnakes/ppa
- sudo apt update
- sudo apt install -y python3.7
script:
- python3.7 --version
- python3.7 .travis/slack_notification.py
after_script:
- echo 'running after_script'
notifications:
  email:
   on_success: always
   on_failure: always
